// Japanese station names (…駅), keyed by the romaji display name used in the
// seed data. Built by hand for Tokyo's covered stations; used on /ja pages so
// station names render in Japanese. Unmapped names fall back to the romaji.
export const STATION_JA: Record<string, string> = {
  "Kita-senju Station": "北千住駅",
  "Ayase Station": "綾瀬駅",
  "Kita-Ayase Station": "北綾瀬駅",
  "Nishiarai Station": "西新井駅",
  "Nishi-Nippori Station": "西日暮里駅",
  "Nippori Station": "日暮里駅",
  "Machiya Station": "町屋駅",
  "Nihonbashi Station": "日本橋駅",
  "Chitose-Karasuyama Station": "千歳烏山駅",
  "Komazawa-daigaku Station": "駒沢大学駅",
  "Shin-Nakano Station": "新中野駅",
  "Naka-Okachimachi Station": "仲御徒町駅",
  "Meguro Station": "目黒駅",
  "Ogikubo Station": "荻窪駅",
  "Gaienmae Station": "外苑前駅",
  "Toyocho Station": "東陽町駅",
  "Shinjuku-nishiguchi Station": "新宿西口駅",
  "Itabashi-kuyakusho-mae Station": "板橋区役所前駅",
  "Korakuen Station": "後楽園駅",
  "Kamata Station": "蒲田駅",
  "Ikebukuro Station": "池袋駅",
  "Akebonobashi Station": "曙橋駅",
  "Kinshicho Station": "錦糸町駅",
  "Ichigaya Station": "市ケ谷駅",
  "Akabane Station": "赤羽駅",
  "Okachimachi Station": "御徒町駅",
  "Ebisu Station": "恵比寿駅",
  "Shinjuku Station": "新宿駅",
  "Shibuya Station": "渋谷駅",
  "Keisei-Ueno Station": "京成上野駅",
  "Tamachi Station": "田町駅",
  "Gotanda Station": "五反田駅",
  "Shinagawa Station": "品川駅",
  "Ueno Station": "上野駅",
  "Hongo-sanchome Station": "本郷三丁目駅",
  "Todai-mae Station": "東大前駅",
  "Kasuga Station": "春日駅",
  "Edogawabashi Station": "江戸川橋駅",
  "Nezu Station": "根津駅",
  "Myogadani Station": "茗荷谷駅",
  "Awajicho Station": "淡路町駅",
  "Ochanomizu Station": "御茶ノ水駅",
  "Suehirocho Station": "末広町駅",
  "Ningyocho Station": "人形町駅",
  "Roppongi-itchome Station": "六本木一丁目駅",
  "Nishi-Shinjuku Station": "西新宿駅",
  "Hatsudai Station": "初台駅",
  "Jiyugaoka Station": "自由が丘駅",
  "Higashi-Koenji Station": "東高円寺駅",
  "Higashi-Nakano Station": "東中野駅",
  "Sangenjaya Station": "三軒茶屋駅",
  "Ikejiri-Ohashi Station": "池尻大橋駅",
  "Oshima Station": "大島駅",
  "Kameido Station": "亀戸駅",
  "Aomono-Yokocho Station": "青物横丁駅",
  "Shinagawa Seaside Station": "品川シーサイド駅",
  "Osaki Station": "大崎駅",
  "Nerima Station": "練馬駅",
  "Toshimaen Station": "豊島園駅",
  "Kasai Station": "葛西駅",
  "Kanamachi Station": "金町駅",
  "Tokyo Station": "東京駅",
  "Yurakucho Station": "有楽町駅",
  "Otemachi Station": "大手町駅",
  "Kanda Station": "神田駅",
  "Akihabara Station": "秋葉原駅",
  "Jimbocho Station": "神保町駅",
  "Ginza Station": "銀座駅",
  "Ginza-itchome Station": "銀座一丁目駅",
  "Kayabacho Station": "茅場町駅",
  "Kodenmacho Station": "小伝馬町駅",
  "Kyobashi Station": "京橋駅",
  "Tsukiji Station": "築地駅",
  "Hatchobori Station": "八丁堀駅",
  "Shinjuku-sanchome Station": "新宿三丁目駅",
  "Omori Station": "大森駅",
  "Otsuka Station": "大塚駅",
  "Sugamo Station": "巣鴨駅",
  "Shinjuku (West Exit) Station": "新宿駅（西口）",
  "Waseda Station": "早稲田駅",
  "Umejima Station": "梅島駅",
  "Toranomon Station": "虎ノ門駅",
  "Yotsuya Station": "四ツ谷駅",
  "Iidabashi Station": "飯田橋駅",
  "Ogikubo (South Exit) Station": "荻窪駅（南口）",
  "Hirai Station": "平井駅",
  "Koiwa Station": "小岩駅",
  "Nishi-Kasai Station": "西葛西駅",
  "Mizue Station": "瑞江駅",
  "Hibiya Station": "日比谷駅",
  "Nakameguro Station": "中目黒駅",
  "Daikanyama Station": "代官山駅",
  "Nijubashimae Station": "二重橋前駅",
  "Futako-Tamagawa Station": "二子玉川駅",
  "Mita Station": "三田駅",
  "Roppongi Station": "六本木駅",
  "Azabu-Juban Station": "麻布十番駅",
  "Onarimon Station": "御成門駅",
  "Shibakoen Station": "芝公園駅",
  "Akabanebashi Station": "赤羽橋駅",
  "Seibu-Shinjuku Station": "西武新宿駅",
  "Takadanobaba Station": "高田馬場駅",
  "Shimbashi Station": "新橋駅",
  "Den-en-chofu Station": "田園調布駅",
  "Sasazuka Station": "笹塚駅",
  "Asakusa Station": "浅草駅",
  "Higashi-Shinjuku Station": "東新宿駅",
  "Meiji-jingumae Station": "明治神宮前駅",
  "Higashi-Ginza Station": "東銀座駅",
  "Shinjuku-Gyoemmae Station": "新宿御苑前駅",
  "Omotesando Station": "表参道駅",
  "Ochiai Station": "落合駅",
  "Koenji Station": "高円寺駅",
  "Nakano Station": "中野駅",
  "Gakugei-Daigaku Station": "学芸大学駅",
  "Toritsu-Daigaku Station": "都立大学駅",
  "Keikyu Kamata Station": "京急蒲田駅",
  "Fudo-mae Station": "不動前駅",
  "Tobu-Nerima Station": "東武練馬駅",
  "Setagaya-Daita Station": "世田谷代田駅",
  "Nishi-Shinjuku-gochome Station": "西新宿五丁目駅",
  "Seijogakuen-mae Station": "成城学園前駅",
  "Oizumi-gakuen Station": "大泉学園駅",
  "Asakusabashi Station": "浅草橋駅",
  "Yotsuya-sanchome Station": "四谷三丁目駅",
  "Monzen-Nakacho Station": "門前仲町駅",
  "Shinsen Station": "神泉駅",
  "Nakano-fujimicho Station": "中野富士見町駅",
  "Toranomon Hills Station": "虎ノ門ヒルズ駅",
  "Shimokitazawa Station": "下北沢駅",
  "Kuramae Station": "蔵前駅",
  "Tawaramachi Station": "田原町駅",
  "Fudomae Station": "不動前駅",
  "Nogizaka Station": "乃木坂駅",
  "Oshiage Station": "押上駅",
  "Honjo-Azumabashi Station": "本所吾妻橋駅",
  "Shimura-sakaue Station": "志村坂上駅",
  "Tobu-Shimoakatsuka Station": "東武下赤塚駅",
  "Narimasu Station": "成増駅",
  "Oyama Station": "大山駅",
  "Kameari Station": "亀有駅",
  "Shin-Koiwa Station": "新小岩駅",
  "Aoto Station": "青砥駅",
  "Oji Station": "王子駅",
  "Tabata Station": "田端駅",
  "Higashi-Jujo Station": "東十条駅",
  "Tochomae Station": "都庁前駅",
  "Kitasenju Station": "北千住駅",
  "Ueno-Hirokoji Station": "上野広小路駅",
  "Kamiyacho Station": "神谷町駅",
  "Asagaya Station": "阿佐ケ谷駅",
  "Musashi-Koyama Station": "武蔵小山駅",
  "Gokokuji Station": "護国寺駅",
  "Hiroo Station": "広尾駅",
  "Shakujii-koen Station": "石神井公園駅",
  "Hatagatadai Station": "旗の台駅",
  "Shin-Itabashi Station": "新板橋駅",
  "Ushigome-Kagurazaka Station": "牛込神楽坂駅",
  "Hamadayama Station": "浜田山駅",
  "Yoga Station": "用賀駅",
  "Higashi-Ojima Station": "東大島駅",
  "Takeshiba Station": "竹芝駅",
  "Toyosu Station": "豊洲駅",
  "Kiba Station": "木場駅",
  "Ojima Station": "大島駅",
  "Kokusai-tenjijo Station": "国際展示場駅",
  "Ogawamachi Station": "小川町駅",
  "Akasaka-mitsuke Station": "赤坂見附駅",
  "Tokyo Teleport Station": "東京テレポート駅",
  "Shin-Okubo Station": "新大久保駅",
  "Hatanodai Station": "旗の台駅",
  "Samezu Station": "鮫洲駅",
  "Kojiya Station": "糀谷駅",
  "Kyodo Station": "経堂駅",
  "Nogata Station": "野方駅",
  "Ekoda Station": "江古田駅",
  "Higashi-Ikebukuro Station": "東池袋駅",
  "Uguisudani Station": "鶯谷駅",
  "Inaricho Station": "稲荷町駅",
  "Minamisunamachi Station": "南砂町駅",
  "Takashimadaira Station": "高島平駅",
  "Komagome Station": "駒込駅",
  "Uchisaiwaicho Station": "内幸町駅",
  "Hikarigaoka Station": "光が丘駅",
  "Haneda Airport Terminal 3 Station": "羽田空港第3ターミナル駅",
  "Higashi-Kitazawa Station": "東北沢駅",
  "Oimachi Station": "大井町駅",
  "Tennozu Isle Station": "天王洲アイル駅",
  "Shinjuku-gyoenmae Station": "新宿御苑前駅",
  "Takanawa Gateway Station": "高輪ゲートウェイ駅",
  "Tameike-Sanno Station": "溜池山王駅",
  "Oshiage (Skytree) Station": "押上（スカイツリー前）駅",
  "Minami-Senju Station": "南千住駅",
  "Kasai-Rinkai-Koen Station": "葛西臨海公園駅",
  "Nishi-Ogikubo Station": "西荻窪駅",
  "Ryogoku Station": "両国駅",
  "Mejiro Station": "目白駅",
};

export function stationNameJa(name: string): string {
  return STATION_JA[name] || name;
}

// Japanese rail-line names, keyed by the English name in the seed data.
export const LINE_JA: Record<string, string> = {
  "Chiyoda": "千代田線", "Fukutoshin": "副都心線", "Ginza": "銀座線", "Hanzomon": "半蔵門線",
  "Hibiya": "日比谷線", "JR Chuo": "JR中央線", "JR Chuo-Sobu": "JR中央・総武線",
  "JR Keihin-Tohoku": "JR京浜東北線", "JR Sobu": "JR総武線", "JR Yamanote": "JR山手線",
  "Keio": "京王線", "Marunouchi": "丸ノ内線", "Namboku": "南北線", "Odakyu": "小田急線",
  "Rinkai": "りんかい線", "Toei Asakusa": "都営浅草線", "Toei Mita": "都営三田線",
  "Toei Oedo": "都営大江戸線", "Toei Shinjuku": "都営新宿線", "Tokaido Shinkansen": "東海道新幹線",
  "Tokyo Monorail": "東京モノレール", "Tokyu Meguro": "東急目黒線", "Tokyu Oimachi": "東急大井町線",
  "Tokyu Toyoko": "東急東横線", "Tozai": "東西線", "Tsukuba Express": "つくばエクスプレス",
  "Yurakucho": "有楽町線", "Yurikamome": "ゆりかもめ",
};

export function lineNameJa(name: string): string {
  return LINE_JA[name] || name;
}
