import type { Metadata } from "next";
import Link from "next/link";
import { allAreaPhotos } from "@/lib/media";
import { allCategoryImages } from "@/lib/cafe-image";

export const metadata: Metadata = {
  title: "Photo credits",
  description: "Image attributions for WorkingCafes.",
  alternates: { canonical: "/credits", languages: { en: "/credits", ja: "/ja/credits", "x-default": "/credits" } },
};

export default function CreditsPage() {
  const photos = allAreaPhotos();
  return (
    <div>
      <p className="breadcrumb">
        <Link href="/">Home</Link> / Photo credits
      </p>
      <h1>Photo credits</h1>
      <p className="lede">
        Area photos come from Wikimedia Commons under free licenses. Thank you to the photographers.
      </p>

      <h2>Area photos</h2>
      <ul>
        {photos.map((p) => (
          <li key={p.slug} style={{ margin: "6px 0" }}>
            <strong style={{ textTransform: "capitalize" }}>{p.slug}</strong>: {p.title} by {p.author},{" "}
            {p.license} (
            <a href={p.source} target="_blank" rel="noopener noreferrer">
              source
            </a>
            ).
          </li>
        ))}
      </ul>

      <h2>Cafe category photos</h2>
      <p className="lede">
        When a cafe has no photo of its own, we show a representative image for its chain or type.
        These come from Wikimedia Commons (Creative Commons), Openverse/Flickr (Creative Commons),
        Pexels, Pixabay, and Unsplash — each under a license that permits this use. Thank you to the photographers.
      </p>
      <ul>
        {allCategoryImages().map((c, i) => (
          <li key={`${c.key}-${i}`} style={{ margin: "6px 0" }}>
            <strong style={{ textTransform: "capitalize" }}>{c.key.replace(/_/g, " ")}</strong>: by {c.author},{" "}
            {c.license} (
            <a href={c.page} target="_blank" rel="noopener noreferrer">
              source
            </a>
            ).
          </li>
        ))}
      </ul>

      <p className="muted">
        Other area cards use original illustrations generated by WorkingCafes. Base location data is
        © OpenStreetMap contributors (ODbL); maps and cafe photos via Google.
      </p>
    </div>
  );
}
