import type { Metadata } from "next";
import Link from "next/link";
import { allAreaPhotos } from "@/lib/media";

export const metadata: Metadata = {
  title: "Photo credits",
  description: "Image attributions for WorkingCafes.",
  alternates: { canonical: "/credits" },
};

export default function CreditsPage() {
  const photos = allAreaPhotos();
  return (
    <div>
      <p className="breadcrumb">
        <Link href="/">Home</Link> / Photo credits
      </p>
      <h1>Photo credits</h1>
      <p className="lede">
        Area photos come from Wikimedia Commons under free licenses. Thank you to the photographers.
      </p>

      <h2>Area photos</h2>
      <ul>
        {photos.map((p) => (
          <li key={p.slug} style={{ margin: "6px 0" }}>
            <strong style={{ textTransform: "capitalize" }}>{p.slug}</strong>: {p.title} by {p.author},{" "}
            {p.license} (
            <a href={p.source} target="_blank" rel="noopener noreferrer">
              source
            </a>
            ).
          </li>
        ))}
      </ul>

      <p className="muted">
        Other area cards use original illustrations generated by WorkingCafes. Base location data is
        © OpenStreetMap contributors (ODbL); maps and cafe photos via Google.
      </p>
    </div>
  );
}
